---
services:
  postgres:
    image: docker.io/library/postgres:16-alpine@sha256:97ff59a4e30e08d1c11bdcd9455e7832368c0572b576c9092cde2df4ae5552a3
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 5s
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${PG_PASS:?database password required}
      POSTGRES_USER: ${PG_USER:-stalwart}
      POSTGRES_DB: ${PG_DB:-stalwart}
    env_file:
      - .env
    networks:
      - app-infra

  keydb:
    image: docker.io/eqalpha/keydb:latest@sha256:6537505c42355ca1f571276bddf83f5b750f760f07b2a185a676481791e388ac
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    healthcheck:
      test: ["CMD-SHELL", "keydb-cli ping | grep PONG"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 3s
    volumes:
      - ./keydb.conf:/etc/keydb/keydb.conf
      - keydb-data:/data
    networks:
      - app-infra

  opensearch:
    image: opensearchproject/opensearch:3.4.0@sha256:1647ce2e07371f1ac8bbad28890a64ef77c5a694a61f656120f0ace09e66bf48
    restart: unless-stopped
    environment:
      discovery.type: single-node
      plugins.security.disabled: true
      OPENSEARCH_JAVA_OPTS: -Xms4g -Xmx8g
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200/_cluster/health || exit 1"]
      start_period: 30s
      interval: 30s
      retries: 5
      timeout: 10s
    volumes:
      - opensearch-data:/usr/share/opensearch/data
    env_file:
      - .env
    networks:
      - app-infra

  stalwart:
    image: ghcr.io/thundersquared/stalwart:0.15.4@sha256:401860d450155621345df07bee510007fa908e2716a17c7927d858c621ed9583
    restart: unless-stopped
    ports:
      - "127.0.0.1:10025:25"
      - "127.0.0.1:10080:80"
      - "127.0.0.1:10110:110"
      - "127.0.0.1:10143:143"
      - "443:443"
      - "465:465"
      - "587:587"
      - "993:993"
      - "995:995"
    cap_add:
      - NET_BIND_SERVICE
    volumes:
      - stalwart-data:/opt/stalwart
    depends_on:
      postgres:
        condition: service_healthy
      keydb:
        condition: service_healthy
      opensearch:
        condition: service_healthy
    env_file:
      - .env
    networks:
      - app-infra

volumes:
  database:
    driver: local
  stalwart-data:
    driver: local
  keydb-data:
    driver: local
  opensearch-data:
    driver: local

networks:
  app-infra:
    external: true
