---
services:
  postgres:
    image: docker.io/library/postgres:16-alpine@sha256:97ff59a4e30e08d1c11bdcd9455e7832368c0572b576c9092cde2df4ae5552a3
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 5s
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${PG_PASS:?database password required}
      POSTGRES_USER: ${PG_USER:-stalwart}
      POSTGRES_DB: ${PG_DB:-stalwart}
    env_file:
      - .env

  keydb:
    image: docker.io/eqalpha/keydb:latest@sha256:6537505c42355ca1f571276bddf83f5b750f760f07b2a185a676481791e388ac
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "keydb-cli ping | grep PONG"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 3s
    volumes:
      - ./keydb.conf:/etc/keydb/keydb.conf
      - keydb-data:/data

  meilisearch:
    image: docker.io/getmeili/meilisearch:v1@sha256:348ba1c1f61101130304370a9522cc5405e6906b64a426dc2fcd5c428a516a98
    restart: unless-stopped
    volumes:
      - meilisearch-data:/meili_data
    environment:
      MEILI_MASTER_KEY: ${MEILI_MASTER_KEY:?master key required}
      MEILI_ENV: production
      MEILI_NO_ANALYTICS: true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7700/health"]
      interval: 5s
      timeout: 1s
      retries: 20
    env_file:
      - .env

  stalwart:
    image: ghcr.io/thundersquared/stalwart:0.13.4@sha256:a0cdd323e98bd39d586ee953bb574b5247d3595fa016c38c89a9fe974b689117
    restart: unless-stopped
    ports:
      - "127.0.0.1:3001:8080"
      - "127.0.0.1:3002:443"
      - "465:465"
      - "587:587"
      - "993:993"
    volumes:
      - stalwart-data:/opt/stalwart
    environment:
      STALWART_STORE__URL: "postgres://${PG_USER:-stalwart}:${PG_PASS}@postgres:5432/${PG_DB:-stalwart}"
      STALWART_FTS__URL: "meilisearch://meilisearch:7700?key=${MEILI_MASTER_KEY}"
      STALWART_CACHE__URL: "redis://keydb:6379"
    depends_on:
      postgres:
        condition: service_healthy
      keydb:
        condition: service_healthy
      meilisearch:
        condition: service_healthy
    env_file:
      - .env

volumes:
  database:
    driver: local
  stalwart-data:
    driver: local
  keydb-data:
    driver: local
  meilisearch-data:
    driver: local
