version: 2
updates:
  - package-ecosystem: "docker"
    directories:
      - "mx1/containers"
      - "web1/containers"
      - "web2/containers"
      - "web3/containers"
    schedule:
      interval: "weekly"