---
docker_stacks:
  watchtower:
    env_file: false
    state: restarted
  cloudflared:
    env_file: true
    state: present
  cobalt:
    env_file: true
    state: present
  calcom:
    env_file: true
    state: present
