services:
  webmail:
    image: ghcr.io/linagora/tmail-web:release@sha256:aa0659fdf2a2a21cc183fa6b30100f4200458ce3477de26f1418d902a2068a35
    container_name: webmail
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    ports:
      - "127.0.0.1:3001:80"
    volumes:
      - ./env.file:/usr/share/nginx/html/assets/env.file
    networks:
      - app-infra

networks:
  app-infra:
    external: true
