---
- name: Ensure /opt/containers exists
  file:
    path: /opt/containers
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Copy containers directory to remote node
  copy:
    src: "{{ playbook_dir }}/../containers/"
    dest: /opt/containers/
    owner: root
    group: root
    mode: '0755'
  notify: Restart containers

- name: Create shared app-infra Docker network
  community.docker.docker_network:
    name: app-infra
    enable_ipv6: "{{ (lookup('env', 'DOCKER_IPV6_SUBNET') | length > 0) | bool }}"
    ipam_config: "{{ [{'subnet': lookup('env', 'DOCKER_IPV6_SUBNET')}] if (lookup('env', 'DOCKER_IPV6_SUBNET') | length > 0) else omit }}"
    internal: false
    scope: "global"
    state: present

- name: Add PG_PASS to stalwart .env
  lineinfile:
    path: /opt/containers/stalwart/.env
    line: PG_PASS={{ lookup('env', 'STALWART_PG_PASSWORD') }}
    create: yes
    owner: root
    group: root
    mode: '0600'
  when: lookup('env', 'STALWART_PG_PASSWORD') | length > 0

- name: Add MEILI_MASTER_KEY to stalwart .env
  lineinfile:
    path: /opt/containers/stalwart/.env
    line: MEILI_MASTER_KEY={{ lookup('env', 'STALWART_MEILI_MASTER_KEY') }}
    create: yes
    owner: root
    group: root
    mode: '0600'
  when: lookup('env', 'STALWART_MEILI_MASTER_KEY') | length > 0

- name: Deploy docker-compose projects
  community.docker.docker_compose_v2:
    project_src: "/opt/containers/{{ item }}"
    state: present
  loop: "{{ compose_files | default(['watchtower']) }}"
  register: compose_results

# - name: Show compose results
#   debug:
#     var: compose_results
