services:
  database:
    image: postgres:18-alpine@sha256:88f300be8635fe8a9ed4c18a68ba497fb6df1215fd2b074895afd027bd3e1006
    restart: unless-stopped
    volumes:
      - database:/var/lib/postgresql/data
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - calcom

  calcom:
    image: calcom/cal.com:v6.1.11@sha256:1406d230d589e23cde342cf6a5f0a5a5071b64f3df9316b82fe38abd6e9fe229
    restart: unless-stopped
    depends_on:
      database:
        condition: service_healthy
    ports:
      - "127.0.0.1:3003:3000"
    env_file:
      - .env
    networks:
      - calcom
      - app-infra

volumes:
  database:
    driver: local

networks:
  calcom:
    driver: bridge
  app-infra:
    external: true
