- name: Add Envoy GPG key
  command: wget -O- https://apt.envoyproxy.io/signing.key | gpg --dearmor -o /etc/apt/keyrings/envoy-keyring.gpg
  args:
    creates: /etc/apt/keyrings/envoy-keyring.gpg

- name: Get system architecture
  command: dpkg --print-architecture
  register: arch

- name: Add Envoy repository
  lineinfile:
    path: /etc/apt/sources.list.d/envoy.list
    line: "deb [arch={{ arch.stdout }} signed-by=/etc/apt/keyrings/envoy-keyring.gpg] https://apt.envoyproxy.io {{ ansible_distribution_release }} main"
    create: yes

- name: Update apt-cache and do dist upgrade
  apt:
    update_cache: yes
    upgrade: dist

- name: Install envoy
  apt:
    name: envoy
    state: present

- name: Ensure envoy is enabled and started
  service:
    name: envoy
    enabled: yes
    state: started

- name: Install nginx
  apt:
    name:
      - nginx
      - libnginx-mod-stream
    state: present

- name: Ensure nginx is enabled and started
  service:
    name: nginx
    enabled: yes
    state: started

- name: Check if reboot required
  stat:
    path: /var/run/reboot-required
  register: reboot_required_file

- name: Reboot if required
  reboot:
  when: reboot_required_file.stat.exists == true
