- name: Add Envoy GPG key
  apt_key:
    url: https://apt.envoyproxy.io/signing.key
    state: present

- name: Add Envoy repository
  lineinfile:
    path: /etc/apt/sources.list.d/envoy.list
    line: "deb [arch={{ ansible_architecture }} signed-by=/etc/apt/trusted.gpg.d/72F9740481B97AD5.gpg] https://apt.envoyproxy.io {{ ansible_distribution_codename }} main"
    create: yes

- name: Update apt-cache and do dist upgrade
  apt:
    update_cache: yes
    upgrade: dist

- name: Install envoy
  apt:
    name: envoy
    state: present

- name: Ensure envoy is enabled and started
  service:
    name: envoy
    enabled: yes
    state: started

- name: Install nginx
  apt:
    name:
      - nginx
      - libnginx-mod-stream
    state: present

- name: Ensure nginx is enabled and started
  service:
    name: nginx
    enabled: yes
    state: started

- name: Check if reboot required
  stat:
    path: /var/run/reboot-required
  register: reboot_required_file

- name: Reboot if required
  reboot:
  when: reboot_required_file.stat.exists == true
