services:
  database:
    image: mysql:8.4@sha256:7fcf7bcd3fa703ff23a2b998e4ed9077e5db570bcc4468459902e33b23d2841d
    env_file: .env
    volumes:
      - database:/var/lib/mysql
    cap_add:
      - SYS_NICE
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -u$$MYSQL_USER -p$$MYSQL_PASSWORD --silent || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 12
    networks:
      - fleet
    restart: unless-stopped

  kv:
    image: valkey/valkey:9-alpine@sha256:68677f85c863830af7836ff07c4a13b7f085ebeff62f4dedb71499ca27d229f2
    command: ["valkey-server", "--appendonly", "yes"]
    networks:
      - fleet
    restart: unless-stopped
    volumes:
      - kv:/data
    healthcheck:
      test: ["CMD-SHELL", "valkey-cli ping | grep PONG"]
      interval: 10s
      timeout: 5s
      retries: 12

  fleet-init:
    image: alpine:3.23@sha256:25109184c71bdad752c8312a8623239686a9a2071e8825f20acb8f2198c3f659
    volumes:
      - logs:/logs
      - data:/fleet
      - vulndb:/vulndb
    command: sh -c "chown -R 100:101 /logs /fleet /vulndb"

  fleet:
    image: ghcr.io/thundersquared/fleet:4.80.1@sha256:05ae7c1f82978ce0da4b93ff75e39fed585725ba62d82b66081b5180a67f3de9
    depends_on:
      database:
        condition: service_healthy
      kv:
        condition: service_healthy
      fleet-init:
        condition: service_completed_successfully
    command: sh -c "/usr/bin/fleet prepare db --no-prompt && /usr/bin/fleet serve"
    ports:
      - "127.0.0.1:3002:${FLEET_SERVER_PORT}"
    env_file: .env
    volumes:
      - logs:/logs
      - data:/fleet
      - vulndb:/vulndb
    networks:
      - app-infra
      - fleet
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://127.0.0.1:${FLEET_SERVER_PORT}/healthz"]
      interval: 10s
      timeout: 5s
      retries: 12
    restart: unless-stopped

volumes:
  database:
  logs:
  data:
  vulndb:
  kv:
networks:
  app-infra:
    external: true
  fleet:
    driver: bridge
