name: Deploy mx1 with Ansible
on:
  workflow_dispatch:
    inputs:
      force_schedule_mode:
        description: 'Force playbook to run in "schedule" mode'
        required: false
        type: boolean
        default: false
  push:
    branches:
      - main
    paths:
      - '.github/workflows/mx1-ansible-deploy.yml'
      - 'mx1/ansible/**'
      - 'mx1/containers/**'
  schedule:
    - cron: '0 0 * * *'  # Every day at midnight
jobs:
  run-ansible:
    runs-on: ubuntu-latest
    environment: mx1
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6.0.1
      - name: Cache pip3
        uses: actions/cache@v5.0.1
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('mx1/ansible/requirements.yml') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Cache Ansible Galaxy requirements
        uses: actions/cache@v5.0.1
        with:
          path: ~/.ansible
          key: ansible-galaxy-${{ hashFiles('mx1/ansible/requirements.yml') }}
          restore-keys: |
            ansible-galaxy-
      - name: Install Ansible
        run: pip3 install ansible==12.1.0 mitogen==0.3.29
      - name: Set up inventory with secrets and SSH key
        run: |
          if [ -z "${{ secrets.HOST }}" ] || [ -z "${{ secrets.USER }}" ]; then
            echo "HOST or USER secret is missing!" >&2
            exit 1
          fi
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | base64 --decode > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H "${{ secrets.HOST }}" >> ~/.ssh/known_hosts
          echo "${{ secrets.HOST }} ansible_user=${{ secrets.USER }} ansible_ssh_private_key=~/.ssh/id_ed25519" > inventory
      - name: Install Ansible Galaxy requirements
        id: galaxy
        run: |
          ansible-galaxy install -r mx1/ansible/requirements.yml --force-with-deps
      - name: Run Ansible Playbook
        env:
          ANSIBLE_CONFIG: mx1/ansible/ansible.cfg
          BORG_REPOSITORY: ${{ secrets.BORG_REPOSITORY }}
          BORG_PASSPHRASE: ${{ secrets.BORG_PASSPHRASE }}
          BORG_HEARTBEAT_URL: ${{ secrets.BORG_HEARTBEAT_URL }}
          STALWART_PG_PASSWORD: ${{ secrets.STALWART_PG_PASSWORD }}
          STALWART_OPENSEARCH_PASSWORD: ${{ secrets.STALWART_OPENSEARCH_PASSWORD }}
          GHCR_USERNAME: ${{ secrets.GHCR_USERNAME }}
          GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
          DOCKER_IPV6_SUBNET: ${{ secrets.DOCKER_IPV6_SUBNET }}
          SCHEDULED_RUN: ${{ github.event_name == 'schedule' || github.event.inputs.force_schedule_mode == 'true' }}
        run: |
          ansible-playbook -i inventory mx1/ansible/playbook.yml --private-key ~/.ssh/id_ed25519
