name: Deploy web3 with Ansible
permissions:
  contents: read
on:
  workflow_dispatch:
    inputs:
      force_schedule_mode:
        description: 'Force playbook to run in "schedule" mode'
        required: false
        type: boolean
        default: false
  push:
    branches:
      - main
    paths:
      - '.github/workflows/web3-ansible-deploy.yml'
      - 'web3/ansible/**'
      - 'web3/containers/**'
  schedule:
    - cron: '0 0 * * *'  # Every day at midnight
jobs:
  run-ansible:
    runs-on: ubuntu-latest
    environment: web3
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6.0.2
      - name: Cache pip3
        uses: actions/cache@v5.0.3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('web3/ansible/requirements.yml') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Cache Ansible Galaxy requirements
        uses: actions/cache@v5.0.3
        with:
          path: ~/.ansible
          key: ansible-galaxy-${{ hashFiles('web3/ansible/requirements.yml') }}
          restore-keys: |
            ansible-galaxy-
      - name: Install Ansible
        run: pip3 install ansible==13.2.0 mitogen==0.3.38
      - name: Set up inventory with secrets and SSH key
        run: |
          if [ -z "${{ secrets.HOST }}" ] || [ -z "${{ secrets.USER }}" ]; then
            echo "HOST or USER secret is missing!" >&2
            exit 1
          fi
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | base64 --decode > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H "${{ secrets.HOST }}" >> ~/.ssh/known_hosts
          echo "${{ secrets.HOST }} ansible_user=${{ secrets.USER }} ansible_ssh_private_key=~/.ssh/id_ed25519" > inventory
      - name: Install Ansible Galaxy requirements
        run: |
          ansible-galaxy install -r web3/ansible/requirements.yml --force-with-deps
      - name: Run Ansible Playbook
        env:
          ANSIBLE_CONFIG: web3/ansible/ansible.cfg
          CLOUDFLARED_TOKEN: ${{ secrets.CLOUDFLARED_TOKEN }}
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
          GHCR_USERNAME: ${{ secrets.GHCR_USERNAME }}
          GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
          DOCKER_IPV6_SUBNET: ${{ secrets.DOCKER_IPV6_SUBNET }}
          CROWDSEC_TOKEN: ${{ secrets.CROWDSEC_TOKEN }}
          SCHEDULED_RUN: ${{ github.event_name == 'schedule' || github.event.inputs.force_schedule_mode == 'true' }}
        run: |
          ansible-playbook -i inventory web3/ansible/playbook.yml --private-key ~/.ssh/id_ed25519
